In [1]:
import os
from dotenv import load_dotenv
from statsbombpy import sb
import pandas as pd
# Load environment variables from .env file (if it exists)
load_dotenv()

# Set credentials if available
username = os.getenv('SB_USERNAME')
password = os.getenv('SB_PASSWORD')

if username and password:
    print("Credentials loaded successfully")
else:
    print("No credentials found - using open data access only")

Credentials loaded successfully

In [2]:
sb.competitions()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,73,317,Mexico,Liga MX,male,False,False,2024/2025,2025-08-30T16:14:20.970616,2025-08-30T16:14:20.970616,2025-08-30T16:14:20.970616,2025-08-30T16:14:20.970616
1,73,281,Mexico,Liga MX,male,False,False,2023/2024,2024-12-20T23:40:31.103974,2024-12-20T23:40:31.103974,2024-12-20T23:40:31.103974,2024-12-20T23:40:31.103974
2,73,235,Mexico,Liga MX,male,False,False,2022/2023,2024-09-28T11:05:11.667984,2024-09-28T11:05:11.667984,2024-09-28T11:05:11.667984,2024-09-28T11:05:11.667984
3,73,108,Mexico,Liga MX,male,False,False,2021/2022,2024-12-10T08:59:57.612449,2024-12-10T08:59:57.612449,2024-12-10T08:59:57.612449,2024-12-10T08:59:57.612449

In [19]:
matches_24_25 = sb.matches(competition_id=73, season_id=317)

matches_24_25.to_parquet("../data/raw/ligamx/season_317_24_25/matches.parquet")

In [20]:
matches_23_24 = sb.matches(competition_id=73, season_id=281)
matches_23_24.to_parquet("../data/raw/ligamx/season_281_23_24/matches.parquet")

matches_22_23 = sb.matches(competition_id=73, season_id=235)
matches_22_23.to_parquet("../data/raw/ligamx/season_235_22_23/matches.parquet")

matches_21_22 = sb.matches(competition_id=73, season_id=108)
matches_21_22.to_parquet("../data/raw/ligamx/season_108_21_22/matches.parquet")

In [ ]:
events_24_25 = sb.competition_events(
    country="Mexico",
    gender="male",
    division= "Liga MX",
    season= "2024/2025"
)

KeyboardInterrupt:

In [32]:
events_24_25.to_parquet("../data/raw/ligamx/season_317_24_25/events.parquet")

In [33]:
events_23_24 = sb.competition_events(
    country="Mexico",
    gender="male",
    division= "Liga MX",
    season= "2023/2024"
)

c:\Users\carls\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsbombpy\sb.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  competition_events = pd.concat(

In [34]:
events_23_24.to_parquet("../data/raw/ligamx/season_281_23_24/events.parquet")

In [35]:
events_22_23 = sb.competition_events(
    country="Mexico",
    gender="male",
    division= "Liga MX",
    season= "2022/2023"
)
events_22_23.to_parquet("../data/raw/ligamx/season_235_22_23/events.parquet")

c:\Users\carls\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsbombpy\sb.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  competition_events = pd.concat(

In [36]:
events_21_22 = sb.competition_events(
    country="Mexico",
    gender="male",
    division= "Liga MX",
    season= "2021/2022"
)
events_21_22.to_parquet("../data/raw/ligamx/season_108_21_22/events.parquet")

c:\Users\carls\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsbombpy\sb.py:160: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  competition_events = pd.concat(

In [37]:
events_21_22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1029393 entries, 0 to 1029392
Columns: 135 entries, 50_50 to under_pressure
dtypes: float64(24), int64(8), object(103)
memory usage: 1.0+ GB

In [39]:
team_season_stats = sb.team_season_stats(competition_id=73, season_id=317)

team_season_stats.head()

,account_id,team_name,team_id,competition_id,competition_name,season_id,season_name,team_female,team_season_matches,team_season_minutes,...,team_season_obv_shot_conceded_pg,team_season_obv_defensive_action_conceded_pg,team_season_obv_dribble_carry_conceded_pg,team_season_obv_gk_conceded_pg,team_season_passes_pg,team_season_successful_passes_pg,team_season_passes_conceded_pg,team_season_successful_passes_conceded_pg,team_season_op_passes_pg,team_season_op_passes_conceded_pg
0,41100,América,1229,73,Liga MX,317,2024/2025,False,47,None,...,-0.165049,0.342086,0.580708,-0.115983,507.191489,428.106383,434.765957,350.234043,459.404255,388.510638
1,41100,Atlas,1296,73,Liga MX,317,2024/2025,False,36,None,...,-0.083851,0.218912,0.811222,-0.154005,411.222222,318.500000,487.083333,394.277778,356.250000,434.638889
2,41100,Cruz Azul,1224,73,Liga MX,317,2024/2025,False,42,None,...,-0.008047,0.276153,0.518214,-0.258176,525.571429,436.500000,417.404762,335.595238,474.642857,367.095238
3,41100,Guadalajara,1297,73,Liga MX,317,2024/2025,False,35,None,...,-0.029194,0.255926,0.688811,-0.027122,481.028571,389.600000,444.685714,360.228571,429.571429,391.485714
4,41100,León,1302,73,Liga MX,317,2024/2025,False,36,None,...,-0.102874,0.288314,0.769489,-0.111729,447.472222,360.861111,471.055556,386.888889,397.833333,420.888889

In [42]:
americas_24_25 = team_season_stats[team_season_stats['team_name'] == 'América']
americas_24_25

americas_24_25.columns

Index(['account_id', 'team_name', 'team_id', 'competition_id',
       'competition_name', 'season_id', 'season_name', 'team_female',
       'team_season_matches', 'team_season_minutes',
       ...
       'team_season_obv_shot_conceded_pg',
       'team_season_obv_defensive_action_conceded_pg',
       'team_season_obv_dribble_carry_conceded_pg',
       'team_season_obv_gk_conceded_pg', 'team_season_passes_pg',
       'team_season_successful_passes_pg', 'team_season_passes_conceded_pg',
       'team_season_successful_passes_conceded_pg', 'team_season_op_passes_pg',
       'team_season_op_passes_conceded_pg'],
      dtype='object', length=181)

In [48]:
# sb.player_season_stats(competition_id=73, season_id=317)[['player_name', 'player_season_assists_90']]

                         player_name  player_season_assists_90
0                      Alexis Méndez                  0.000000
1         Fernando David Arce Juárez                  0.000000
2                  Cade Dylan Cowell                  0.128711
3     Sergio Armando Aguayo Castillo                  0.000000
4           Ventura Alvarado Aispuro                  0.000000
..                               ...                       ...
631              Sergio Ramos García                  0.000000
632                 Pau López Sabata                  0.000000
633           Sergio Canales Madrazo                  0.286785
634  Francisco José Villalba Rodrigo                  0.126767
635              Óliver Torres Muñoz                  0.069206

[636 rows x 2 columns]

In [53]:
matches_24_25 = pd.read_parquet("../data/raw/ligamx/season_317_24_25/matches.parquet")
matches_24_25.head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,attendance,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3939828,2024-07-13,03:05:00.000,Mexico - Liga MX,2024/2025,Atlas,Tigres UANL,1,1,None,...,2024-07-28T14:19:51.119184,2,Apertura,Estadio Jalisco,Jorge Abraham Camacho Peregrina,Beñat San José Gil,Veljko Paunovic,1.1.0,2,2
1,3939831,2024-07-14,01:10:00.000,Mexico - Liga MX,2024/2025,Toluca,Juárez,3,2,None,...,2024-07-17T19:59:49.032573,2,Apertura,Estadio Nemesio Díez,Vicente Jassiel Reynoso Arce,Renato Manuel Alves Paiva,"Maurício Nogueira Barbieri, Claudio Andrés del...",1.1.0,2,2
2,3939858,2024-08-25,01:00:00.000,Mexico - Liga MX,2024/2025,Tigres UANL,Guadalajara,1,1,None,...,2024-09-09T15:24:06.686718,5,Apertura,Estadio Universitario de Nuevo León,Daniel Quintero Huittrón,Veljko Paunovic,Fernando Rubén Gago,1.1.0,2,2
3,3939953,2024-11-06,03:05:00.000,Mexico - Liga MX,2024/2025,Pumas UNAM,Querétaro,2,0,None,...,2024-11-30T08:10:15.512997,16,Apertura,Estadio Olímpico de Universitario (Ciudad de M...,Daniel Quintero Huittrón,Gustavo Alberto Lema,Mauro Néstor Gerk Larrea,1.1.0,2,2
4,3939874,2024-09-14,03:00:00.000,Mexico - Liga MX,2024/2025,Necaxa,Pumas UNAM,2,0,None,...,2024-09-24T05:22:49.454648,7,Apertura,Estadio Victoria de Aguascalientes,Katia Itzel García,Eduardo Fentanes Orozco,Gustavo Alberto Lema,1.1.0,2,2

In [55]:
sb.player_match_stats(3939874)

,account_id,match_id,team_id,team_name,player_id,player_name,player_match_minutes,player_match_np_xg_per_shot,player_match_np_xg,player_match_np_shots,...,player_match_claim_success,player_match_da_aggressive_distance,player_match_goals_conceded,player_match_gsaa,player_match_gk_positioning_error,player_match_positive_outcome_score,player_match_npot_psxg_faced,player_match_save_ratio,player_match_gsaa_ratio,player_match_npot_shots_faced
0,41100,3939874,1301,Pumas UNAM,11500,Ignacio Pussetto,83.933334,0.184412,0.553237,3,...,None,79.731537,0,0.000000,NaN,0.508475,0.000000,0.000000,NaN,0
1,41100,3939874,1221,Necaxa,27762,Ezequiel Unsain,99.900000,NaN,0.000000,0,...,None,14.205808,0,0.002977,1.557620,0.032051,0.002977,1.000000,0.002977,1
2,41100,3939874,1301,Pumas UNAM,23263,Lisandro Magallán,99.900000,NaN,0.000000,0,...,None,43.578793,0,0.000000,NaN,0.153846,0.000000,0.000000,NaN,0
3,41100,3939874,1301,Pumas UNAM,26318,Rogelio Funes Mori,64.283330,NaN,0.000000,0,...,None,42.202213,0,0.000000,NaN,0.370370,0.000000,0.000000,NaN,0
4,41100,3939874,1221,Necaxa,28529,Fernando Arce,99.900000,0.240382,0.721146,3,...,None,56.436817,0,0.000000,NaN,0.153846,0.000000,0.000000,NaN,0
5,41100,3939874,1301,Pumas UNAM,27897,Ulises Rivas,64.016670,NaN,0.000000,0,...,None,53.375088,0,0.000000,NaN,0.444444,0.000000,0.000000,NaN,0
6,41100,3939874,1301,Pumas UNAM,75305,Guillermo Martínez Ayala,35.616665,0.034582,0.034582,1,...,None,91.888489,0,0.000000,NaN,NaN,0.000000,0.000000,NaN,0
7,41100,3939874,1301,Pumas UNAM,6612,Rubén Duarte,99.900000,0.014254,0.028508,2,...,None,64.906952,0,0.000000,NaN,0.504274,0.000000,0.000000,NaN,0
8,41100,3939874,1221,Necaxa,27902,Alejandro Mayorga,99.900000,NaN,0.000000,0,...,None,49.439522,0,0.000000,NaN,0.134615,0.000000,0.000000,NaN,0
9,41100,3939874,1221,Necaxa,28480,Tomás Badaloni,12.850000,NaN,0.000000,0,...,None,69.493073,0,0.000000,NaN,NaN,0.000000,0.000000,NaN,0
10,41100,3939874,1221,Necaxa,32022,José Paradela,87.050000,0.007304,0.014608,2,...,None,55.936054,0,0.000000,NaN,0.294872,0.000000,0.000000,NaN,0
11,41100,3939874,1301,Pumas UNAM,27889,César Huerta,99.900000,0.068620,0.068620,1,...,None,89.098328,0,0.000000,NaN,0.547009,0.000000,0.000000,NaN,0
12,41100,3939874,1221,Necaxa,37877,Ricardo Monreal,12.850000,NaN,0.000000,0,...,None,49.111172,0,0.000000,NaN,NaN,0.000000,0.000000,NaN,0
13,41100,3939874,1301,Pumas UNAM,136926,Pablo Bennevendo Peña,84.150000,0.020720,0.020720,1,...,None,65.792557,0,0.000000,NaN,0.576271,0.000000,0.000000,NaN,0
14,41100,3939874,1221,Necaxa,28815,Agustín Palavecino,74.516670,0.077185,0.231554,3,...,None,66.327393,0,0.000000,NaN,0.448718,0.000000,0.000000,NaN,0
15,41100,3939874,1301,Pumas UNAM,29078,José Luis Caicedo,99.900000,NaN,0.000000,0,...,None,59.441376,0,0.000000,NaN,0.094017,0.000000,0.000000,NaN,0
16,41100,3939874,1221,Necaxa,27887,Bryan Eduardo Garnica Cortéz,87.050000,NaN,0.000000,0,...,None,76.590942,0,0.000000,NaN,0.038462,0.000000,0.000000,NaN,0
17,41100,3939874,1301,Pumas UNAM,31750,Robert Ergas,15.750000,NaN,0.000000,0,...,None,93.096863,0,0.000000,NaN,0.586207,0.000000,0.000000,NaN,0
18,41100,3939874,1301,Pumas UNAM,36949,Julio José González Vela-Alvizu,99.900000,NaN,0.000000,0,...,None,20.610123,2,-0.083891,1.731293,NaN,1.916109,0.666667,-0.013982,6
19,41100,3939874,1221,Necaxa,37916,Agustín Oliveros,99.900000,NaN,0.000000,0,...,None,46.891960,0,0.000000,NaN,0.032051,0.000000,0.000000,NaN,0
20,41100,3939874,1221,Necaxa,41777,Emilio Lara,51.883335,NaN,0.000000,0,...,None,58.586342,0,0.000000,NaN,0.011628,0.000000,0.000000,NaN,0
21,41100,3939874,1221,Necaxa,43309,Alán Montes,99.900000,0.047748,0.047748,1,...,None,40.112404,0,0.000000,NaN,0.064103,0.000000,0.000000,NaN,0
22,41100,3939874,1301,Pumas UNAM,44068,Nathan Silva,99.900000,NaN,0.000000,0,...,None,47.156548,0,0.000000,NaN,0.205128,0.000000,0.000000,NaN,0
23,41100,3939874,1221,Necaxa,57938,Emilio Martínez González,48.016666,NaN,0.000000,0,...,None,43.621105,0,0.000000,NaN,0.057143,0.000000,0.000000,NaN,0
24,41100,3939874,1301,Pumas UNAM,78108,Ali Ávila Vega,15.966666,0.177952,0.177952,1,...,None,44.144363,0,0.000000,NaN,NaN,0.000000,0.000000,NaN,0
25,41100,3939874,1221,Necaxa,89887,Diber Armando Cambindo Abonia,99.900000,0.105018,0.525091,5,...,None,86.280952,0,0.000000,NaN,0.256410,0.000000,0.000000,NaN,0
26,41100,3939874,1301,Pumas UNAM,101509,Piero Quispe,35.883335,NaN,0.000000,0,...,None,73.725769,0,0.000000,NaN,0.365079,0.000000,0.000000,NaN,0
27,41100,3939874,1221,Necaxa,139124,Kevin Duvan Ante Rosero,25.466667,NaN,0.000000,0,...,None,38.010792,0,0.000000,NaN,NaN,0.000000,0.000000,NaN,0
28,41100,3939874,1301,Pumas UNAM,146649,Jorge Ruvalcaba,90.783330,NaN,0.000000,0,...,None,72.951851,0,0.000000,NaN,0.068493,0.000000,0.000000,NaN,0
29,41100,3939874,1221,Necaxa,146650,Heriberto De Jesus Jurado Flores,74.433334,NaN,0.000000,0,...,None,83.718819,0,0.000000,NaN,NaN,0.000000,0.000000,NaN,0
30,41100,3939874,1221,Necaxa,181730,Diego Gómez,25.383333,NaN,0.000000,0,...,None,61.543800,0,0.000000,NaN,NaN,0.000000,0.000000,NaN,0
31,41100,3939874,1301,Pumas UNAM,275441,Rodrigo López Quiñones,9.116667,0.025715,0.025715,1,...,None,99.386032,0,0.000000,NaN,0.545455,0.000000,0.000000,NaN,0

In [58]:
from sklearn.decomposition import PCA
americas_24_25

,account_id,team_name,team_id,competition_id,competition_name,season_id,season_name,team_female,team_season_matches,team_season_minutes,...,team_season_obv_shot_conceded_pg,team_season_obv_defensive_action_conceded_pg,team_season_obv_dribble_carry_conceded_pg,team_season_obv_gk_conceded_pg,team_season_passes_pg,team_season_successful_passes_pg,team_season_passes_conceded_pg,team_season_successful_passes_conceded_pg,team_season_op_passes_pg,team_season_op_passes_conceded_pg
0,41100,América,1229,73,Liga MX,317,2024/2025,False,47,None,...,-0.165049,0.342086,0.580708,-0.115983,507.191489,428.106383,434.765957,350.234043,459.404255,388.510638

In [6]:
lineup = sb.lineups(3939874)
lineup['positions']

KeyError: 'positions'